/**
 * Build the browser half: src/client → lib/client.js (single self-running
 * IIFE, React bundled). Mirrors dsh's scripts/build-client.mjs — lib/client.js
 * is a generated artifact, never hand-edited.
 */
import { readFile, rm, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "vite";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const OUT = resolve(ROOT, "lib", "client.js");

async function main() {
  const hadClient = await readFile(OUT, "utf8").then(
    () => true,
    () => false,
  );
  try {
    await build({ configFile: resolve(ROOT, "vite.config.ts"), logLevel: "info" });
  } catch (err) {
    // A failed build must not leave a stale client.js behind pretending to be
    // current — but do not delete a source-only checkout's hand-written file.
    if (hadClient) {
      console.warn("build failed; keeping existing lib/client.js");
    }
    console.error(String(err && err.message ? err.message : err));
    process.exitCode = 1;
    return;
  }

  // Guard header so consumers can tell a built client from a stale one.
  const banner =
    "/* zcode-wallpaper-engine client — generated by scripts/build-client.mjs. " +
    "Do not hand-edit; edit src/client and re-run `pnpm build`. */\n";
  let body = await readFile(OUT, "utf8");
  if (!body.startsWith("/* zcode-wallpaper-engine client")) {
    body = banner + body;
    await writeFile(OUT, body);
  }
  const kb = (body.length / 1024).toFixed(1);
  console.log(`lib/client.js written (${kb} KB)`);
}

void main();
